alerts:
  email_password: ''
  email_port: 587
  email_recipients: []
  email_smtp: smtp.gmail.com
  email_user: ''
  enable_email: false
  enable_webhook: false
  log_file: security_alerts.json
  webhook_url: ''
detection:
  confidence_threshold: 0.8
  model_path: models/random_forest_model_tuned.joblib
  rate_limit_max: 5
  rate_limit_window: 60
logging:
  backup_count: 5
  file: intrusion_detection.log
  level: INFO
  max_size_mb: 10
monitoring:
  dashboard_host: 127.0.0.1
  dashboard_port: 8080
  enable_web_dashboard: true
  stats_update_interval: 5
network:
  buffer_size: 1000
  interface: auto
  promiscuous_mode: false
